package com.piyumal.todo_app_doodle;

/**
 * Model Class: Represents a single Task entity.
 * Used for Firebase Firestore data mapping.
 */
public class Task {
    // Unique ID generated by Firestore for each document
    private String taskId;
    private String title;
    private String description;

    // Storing Date and Time as Strings for easy UI display
    private String scheduledDate; // e.g., "May 15, 2026"
    private String scheduledTime; // e.g., "10:30 AM"

    // Status flag to track if the task is done
    private boolean isCompleted;

    // System timestamp to sort tasks by creation order
    private long createdAt;

    /**
     * Default No-argument Constructor.
     * CRITICAL: Required by Firebase for Data Snapshot to Object conversion.
     */
    public Task() {}

    /**
     * Parameterized Constructor.
     * Used when creating a new Task instance from the Add Task Dialog.
     */
    public Task(String taskId, String title, String description, String scheduledDate, String scheduledTime, long createdAt) {
        this.taskId = taskId;
        this.title = title;
        this.description = description;
        this.scheduledDate = scheduledDate;
        this.scheduledTime = scheduledTime;
        this.isCompleted = false; // New tasks are uncompleted by default
        this.createdAt = createdAt;
    }

    // --- GETTER METHODS ---
    // These allow Firestore and the TaskAdapter to read the private field values

    public String getTaskId() { return taskId; }
    public String getTitle() { return title; }
    public String getDescription() { return description; }
    public String getScheduledDate() { return scheduledDate; }
    public String getScheduledTime() { return scheduledTime; }
    public boolean isCompleted() { return isCompleted; }
    public long getCreatedAt() { return createdAt; }

    // --- SETTER METHODS ---
    // Used to update specific fields, like marking a task as "Done"

    public void setCompleted(boolean completed) { isCompleted = completed; }
}